---

copy1:
  font-family: Roboto
  font-size: 16px

copy2:
  font-family: Roboto
  font-size: 32px

h1: 
  font-family: proxima extrabold
  font-size: 48px

h2:
  font-family: proxima extrabold
  font-size: 36px

