---

copy1s:
  font-family: Roboto
  font-size: 16px

copy1:
  font-family: Roboto
  font-size: 20px

copy2:
  font-family: Roboto
  font-size: 32px

copy3:
  font-family: proxima regular
  font-size: 32px
  font-weight: '500'

copy4:
  font-family: proxima regular
  font-size: 24px
  font-weight: '500'

h1: 
  font-family: proxima extrabold
  font-size: 48px

h2:
  font-family: proxima extrabold
  font-size: 36px

