---
url: http://256.io/
title: 256 
description: building digital things
keywords: web development, mobile development, mobile apps, full stack development
phone: 9492908989
trackingID: UA-75128355-1
logo: images/logo_1000x1000.jpg
share: images/1200x630.jpg
repo: https://github.com/acidjazz/256
email: kevin@256.io
social:
  facebook: https://www.facebook.com/256llc/
  twitter: https://twitter.com/256llc
  instagram: https://www.instagram.com/256llc/
