---
definery:
  color: '#55C7C0'
  title: DEFINERY
  tagline: a digital product design and innovation company
  detail:
    - I had the honor of working with the Definery team on our first version of <a href="http://definery.io" target="_new">definery.io</a>. For this project we wanted to go for the most innovative and recent (while still compatible) technology.
    - We packed in lots of lively features like clipping, masking, and using blend modes (mix-blend-mode to be precise) for compositing graphic elements, which even worked well with video.  We also hit our target on mobile by dynamically alternating meta tags used to customize the user experience on android devices.  
  links:
    url: http://definery.io/
    github: http://github.com/acidjazz/definery
astro:
  color: '#C8504B'
  title: Astro Studios
  tagline: Creators of Supercharged Brand and Product Experiences.
  links: 
    url: http://www.astrostudios.com/
ap:
  color: '#A49266'
  url: http://www.audemarspiguet.com/
  title: Audemars Piguet
br:
  color: '#221F20'
  url: http://www.bystanderrevolution.org/
  title: Bystander Revolution
daffodil:
  color: '#7F7774'
  url: http://www.daffodildigital.com/
  title: Daffodil Digital
gilman:
  color: '#221f20'
  url: http://gilman.256.tech/
  title: Gilman Brewing Company
sake:
  color: '#73B8B2'
  ur/: http://www.designsakestudio.com/
  title: Designsake Studio
studio:
  color: '#4867aa'
  url: http://www.facebook-studio.com/
  title: Facebook Studio
