---
 definery:
   color: "#3F4C55"
   name: Astro Studios
   url: http://www.astrostudios.com/
 astro:
   color: '#FF002B'
   name: Astro Studios
   url: http://www.astrostudios.com/
 br:
   color: '#221F20'
   name: Bystander Revolution
   url: http://www.bystanderrevolution.org/
 daffodil:
   color: '#ffffff'
   name: Daffodil Digital
   url: http://www.daffodildigital.com/
