---
definery:
  color: '#55C7C0'
  title: DEFINERY
  tagline: a digital product design and innovation company
  detail:
    - For our first version of <a href="http://definery.io" target="_new">definery.io</a>. For this project we wanted to go for the most innovative and recent (while still compatible) technology.
    - We packed in lots of lively features like clipping, masking, and using blend modes (mix-blend-mode to be precise) for compositing graphic elements, which even worked well with video.  We also hit our target on mobile by dynamically alternating meta tags used to customize the user experience on android devices.  
  links:
    url: http://definery.io/
    github: http://github.com/acidjazz/definery
astro:
  color: '#C8504B'
  title: Astro Studios
  tagline: Supercharged Brand and Product Experiences.
  detail:
    - It was a great pleasure working with such an innovative product design agency.
    - This was a major challenge of staying with 100% original and custom functionality and features while keeping an easily modifiable and legible structure of syntactic sugar.
    - With two seperate and fully custom CMS sections, and a couple easter eggs, every section of this project packs a punch.
  links: 
    url: http://www.astrostudios.com/
    github: http://github.com/acidjazz/astro
br:
  color: '#E0483E'
  title: Bystander Revolution
  tagline: Take the power out of bullying
  detail:
    - Going on 3 years, 3,000+ commits, 3 complete renovations, and 10+ campaigns, it's been a great opportunity to take on development and operations for Bystander Revolution.
    - Working with multiple agencies through the years, essentially with MacKenzie Bezos' core team in Seattle, we've tackled all sorts of tasks dealing with preconditioned and user-contributed content, constantly evolving to display it comfortably in multiple easily navigatable interfaces.
  links:
    url: http://www.bystanderrevolution.org/
gilman:
  color: '#c08000'
  title: Gilman Brewing Company
  tagline: Born and brewed in Berkeley, California
  detail:
    - Lots of fun on this project going further than just development and operations and getting involved in creating some cinemagraphs to help make the site come alive.
    - Once launched this project will take advantage of the newer webkit push allowing silent video to auto-play, giving video on mobile without resulting in bulky uncompressed GIFS
  links:
    url: http://gilman.256.tech/
sake:
  color: '#73B8B2'
  title: Designsake Studio
  tagline: For the sake of good design
  detail:
    - Being given such a clean and pretty design and a great rich portfolio of work, building a fluid experience was a pleasure.
    - Built a completely custom SPA experience preloading all images of each section and never refreshing, with loading animations showing realtime loading .
  links:
    url: http://www.designsakestudio.com/
    github: http://github.com/acidjazz/sake
daffodil:
  color: '#EFE047'
  title: Daffodil Digital
  tagline: Helping brands tell their stories
  detail:
    - I wanted to aim for a complete SPA experience, focusing directly on preloading all imagery and using custom loading animations to keep a nice flowing experience
  links:
    url: http://www.daffodildigital.com/
    github: http://github.com/acidjazz/daffodil
ap:
  color: '#A49266'
  title: Audemars Piguet
  tagline: Ultra-luxury swiss watches
  detail:
    - I came aboard briefly to help with the back-end, and was given the pleasure of setting the foundation and structure for v1 of their API.
    - At the end we had successfully centralized all watch and retail store content that drove the site and apps to version-seperated endpoints that match the JSONAPI spec.
  links: 
    url: http://www.audemarspiguet.com/
studio:
  color: '#4867aa'
  title: Facebook Studio
  tagline: Facebook Awards
  detail:
    - Very happy to work on this major collaboration with Facebook. One of the most thorough projects I've had a pleaure to work on, from multiple audits of every check-in to unit testing every piece of functionality.
  links:
    url: http://www.facebook-studio.com/


