---
 definery:
   color: '#55C7C0'
   url: http://www.astrostudios.com/
   title: Definery LLC
 astro:
   color: '#C8504B'
   url: http://www.astrostudios.com/
   title: Astro Studios
 ap:
   color: '#A49266'
   url: http://www.audemarspiguet.com/
   title: Audemars Piguet
 br:
   color: '#221F20'
   url: http://www.bystanderrevolution.org/
   title: Bystander Revolution
 daffodil:
   color: '#7F7774'
   url: http://www.daffodildigital.com/
   title: Daffodil Digital
 gilman:
   color: '#221f20'
   url: http://gilman.256.tech/
   title: Gilman Brewing Company
 sake:
   color: '#73B8B2'
   ur/: http://www.designsakestudio.com/
   title: Designsake Studio
 studio:
   color: '#4867aa'
   url: http://www.facebook-studio.com/
   title: Facebook Studio
